# Default profile for running pipeline on a computer cluster via DRMAA
# interface. See: https://snakemake.readthedocs.io/en/stable/executable.html#profiles
# Usage: e.g. on linux, copy or link this directory under 
# configuration options below.
local-cores: 8
cores: 300
latency-wait: 60
use-conda: true
jobname: BACgastro_{name}.jobid{jobid}
#jobs: "99"
# settings for running on the grid
#drmaa: " -q bio -n {threads} -R \"span[hosts=1]\""
#drmaa-log-dir: out/log/drmaa
